version: 2
updates:
  # Cargo
  - package-ecosystem: "cargo"
    directory: "./"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "executorch-sys/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "examples/hello_world_add/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "examples/hello_world_add_no_std/"
    schedule:
      interval: "monthly"

  # Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
