version: 2
updates:
  # Cargo
  - package-ecosystem: cargo
    directory: ./
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: executorch-sys/
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: examples/hello_world/
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: examples/raw_tensor/
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: examples/no_ndarray/
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: examples/no_std/
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: examples/nano-gpt/
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: examples/llama3/
    schedule:
      interval: monthly

  # Actions
  - package-ecosystem: github-actions
    directory: ./
    schedule:
      interval: monthly
