version: 2
updates:
  # Cargo
  - package-ecosystem: cargo
    directories:
      - executorch/
      - executorch-sys/
      - examples/hello_world/
      - examples/raw_tensor/
      - examples/no_ndarray/
      - examples/no_std/
      - examples/nano-gpt/
      - examples/llama3/
    schedule:
      interval: monthly
    groups:
      rust-patch-updates:
        update-types:
          - "patch"

  # Actions
  - package-ecosystem: github-actions
    directory: ./
    schedule:
      interval: monthly
