[package]
name = "example-nano-gpt"
version = "0.0.0"
edition = "2021"
publish = false


[dependencies]
executorch = { path = "../../", features = [
    "ndarray",
    "data-loader",
    "module",
    "tensor-ptr",
] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
