[package]
publish = false
name = "example-etdump"
version = "0.0.0"
edition = "2021"

[dependencies]
executorch = { path = "../../executorch/", features = [
    "ndarray",
    "data-loader",
    "module",
    "tensor-ptr",
    "etdump",
] }
ndarray = { version = "0.17", default-features = false }
