[package]
publish = false
name = "example-etdump"
version = "0.0.0"
edition = "2021"

[dependencies]
executorch = { path = "../../", features = [
    "ndarray",
    "data-loader",
    "module",
    "tensor-ptr",
    "etdump",
] }
ndarray = { version = "0.16.0", default-features = false }
