[package]
name = "executorch-sys"
version = "0.1.0"
authors = ["Barak Ugav <barakugav@gmail.com>"]
edition = "2021"
description = "Unsafe Rust bindings for Executorch 0.2.1 - On-device AI across mobile, embedded and edge for PyTorch"
readme = "README.md"
repository = "https://github.com/barakugav/executorch-rs"
license = "Apache-2.0"
keywords = [
    "executorch",
    "pytorch",
    "ai",
    "ml",
    "machine-learning",
    "mobile",
    "embedded",
    "edge-device",
    "bindings",
]
categories = [
    "algorithms",
    "mathematics",
    "embedded",
    "no-std",
    "no-std::no-alloc",
]
links = "executorch"

[features]
extension-data-loader = []
extension-module = []

[dependencies]

[build-dependencies]
bindgen = "0.69.4"
cc = "1.1.6"
envsubst = "0.2.1"
