name: Security Vulnerabilities Check

on:
  schedule:
    # runs once a week
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      ############ Setup ############
      - name: Repo checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.77.0
      - name: Install cargo-audit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-audit
          version: 0.20.0
          locked: true

      ############ Checks ############
      - name: Audit
        run: cargo audit -D warnings
        # its enough to only check the top level Cargo.lock because we are in a workspace
        working-directory: executorch
